# Generated by Django 5.1.3 on 2024-11-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0004_alter_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(choices=[(0, 'Nulo'), (1, 'arrendador'), (2, 'arrendatario'), (3, 'administrador')], default='Nulo', max_length=20),
        ),
    ]
